---
apiVersion: apps/v1
kind: Deployment                
metadata:
  name: go-rest-docker           
spec:
  replicas: 3                   
  selector:
    matchLabels:
      app: go-rest-docker        
  template:                      
    metadata:
      labels:                   
        app: go-rest-docker 
    spec:                        
      containers:
      - name: go-rest-docker
        image: ernestaskardzys/go-rest-docker:latest 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service        
metadata:
  name: go-rest-docker-service
spec:
  type: NodePort                
  ports:                         
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: go-rest-docker
